Repository Samfundet/Samfundet, pull requests merged in 2019-09, with the labels that each got.

#440 Unique accepted applicants
  app/controllers/admissions_admin/admissions_controller.rb
  app/views/admissions_admin/admissions/statistics.html.haml
  config/locales/views/admissions_admin/en.yml
  config/locales/views/admissions_admin/no.yml
Labels: admission

#473 Datepicker first day monday
  app/assets/javascripts/sitewide/bind-datepickers.js
Labels: sulten, visual

#474 Upgrade to Ruby v2.5
  .travis.yml
  Gemfile
  Gemfile.lock
Labels: internal
