Repository Samfundet/Samfundet, pull requests merged in 2022-09, with the labels that each got.

#945 Update to ruby 2.7
  .ruby-version
  .travis.yml
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  linux-setup-database.sh
  linux-setup-rvm.sh
Labels: pending

#908 FAQ and table of content new building
  app/assets/javascripts/new_building/faq-dropdown.js
  app/assets/stylesheets/new_building.scss
  app/views/new_building/_FAQ.html.haml
  app/views/new_building/_contact_info.html.haml
  app/views/new_building/_table_of_content.html.haml
  app/views/new_building/index.html.haml
  config/application.rb
  config/locales/views/new_building/en.yml
  config/locales/views/new_building/no.yml
Labels: info pages, pending

#958 [Fix] - Session cookie expiration time
  Gemfile
  Gemfile.lock
  config/initializers/session_store.rb
Labels: bug, dependencies
