Repository Samfundet/Samfundet, pull requests merged in 2023-08, with the labels that each got.

#1028 [Change] Enable phone number input on forgot password form
  app/controllers/applicants_controller.rb
  app/views/applicants/forgot_password.html.haml
  config/locales/views/applicant_sessions/en.yml
  config/locales/views/applicant_sessions/no.yml
  config/locales/views/applicants/en.yml
  config/locales/views/applicants/no.yml
  features/step_definitions/applicants_steps.rb
Labels: admission

#1040 [Bugfix] Fix rule for showing kitchen open text
  app/controllers/sulten/lyche_controller.rb
  app/views/sulten/lyche/_status_box.html.haml
Labels: sulten

#1041 [Bugfix] Fix food_open_date null variable
  app/controllers/sulten/lyche_controller.rb
Labels: bug, sulten

#1039 [Feature] Add applicant E-mail verification
  app/controllers/applicant_sessions_controller.rb
  app/controllers/applicants_controller.rb
  app/helpers/applicant_verification_helper.rb
  app/mailers/verify_email_applicant_mailer.rb
  app/models/applicant.rb
  app/models/email_verification.rb
  app/views/applicants/_form.html.haml
  app/views/verify_email_applicant_mailer/send_applicant_email_verification.text.haml
  config/locales/routes/i18n-routes.yml
  config/locales/views/applicants/en.yml
  config/locales/views/applicants/no.yml
  config/routes.rb
  db/migrate/20230709174101_add_verified_to_applicants.rb
  db/migrate/20230806185604_create_email_verifications.rb
  db/schema.rb
Labels: admission, HIGH PRIORITY

#1025 [Change] Add E-mail confirmation field for applicant registration
  app/controllers/applicants_controller.rb
  app/models/applicant.rb
  app/views/applicants/_form.html.haml
  config/locales/activerecord_en.yml
  config/locales/activerecord_no.yml
  config/locales/models/applicant/en.yml
  config/locales/models/applicant/no.yml
  db/seeds/applicants.seeds.rb
  lib/validators/email_validator.rb
Labels: admission

#1034 [Change] Add restriction for editing status & priority, except for Admission Admin
  app/controllers/admissions_admin/interviews_controller.rb
  app/controllers/admissions_admin/jobs_controller.rb
  app/models/interview.rb
  app/views/admissions_admin/job_applications/show.html.haml
  app/views/admissions_admin/jobs/_jobs_show.html.haml
Labels: admission

#1044 Add line that makes verification email field lowercase
  app/controllers/applicants_controller.rb
Labels: bug, admission

#1036 [Bugfix] Add proper error message when user does not have access to a page + contributors
  CONTRIBUTORS
  app/controllers/application_controller.rb
  config/locales/defaults/en.yml
  config/locales/defaults/no.yml
Labels: bug

#1032 [Bugfix] Force hash and email to be present on reset password form
  app/controllers/applicants_controller.rb
  app/views/applicants/reset_password.html.haml
Labels: bug, admission

#1033 [Change] Remove redirect to new applicant upon login failure
  app/controllers/applicant_sessions_controller.rb
  config/locales/views/applicants/en.yml
Labels: admission
